language: elixir
elixir:
  - 1.3.3
otp_release:
  - 19.2
script:
  - mix deps.get
  - export MIX_ENV=test
  - mix ecto.create
  - mix ecto.migrate
  - mix espec --format doc
services:
  - mysql
sudo: required
notifications:
  recipients:
    - adrianmarino@gmail.com
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('1234') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
