#!/bin/bash
COMMAND=$1

export MIX_ENV=${2:-dev}
export MYSQL_ROOT_PASSWORD=${3:-1234}

echo "=========================================================="
echo "Environment: $MIX_ENV"
echo "Password: $MYSQL_ROOT_PASSWORD"
echo "Command: $COMMAND"
echo "=========================================================="

docker build .
docker-compose run --rm -p3000:3000 points sh -c "$COMMAND"
