#!/bin/bash
export VERSION=${1:-$(mix point.version)}
export MIX_ENV=${2:-dev}
export MYSQL_ROOT_PASSWORD=${3-1234}
export MYSQL_PORT=${4-3306}

echo -e "\n============================================"
echo "VERSION=$VERSION"
echo "MIX_ENV=$MIX_ENV"
echo "============================================"

echo -e "\nStart images..."
docker-compose up
