#!/bin/bash
#------------------------------------------------------------------------------
# Variables
#------------------------------------------------------------------------------
# Users:
  ENTITY_ADMIN=adrianmarino@gmail.com # X company admin user.
  #
  NORMAL_USER_A=a@gmail.com # An X company user.
  NORMAL_USER_B=b@gmail.com # An X company user.
#
CURRENT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
#
#
#
#------------------------------------------------------------------------------
# Include external files
#------------------------------------------------------------------------------
# When include 'lib' file:
#  - Add helper functions/variables for the most frequent tasks.
#  - Execute exercise preconditions(See 'Exercise preconditions' section in exercises/lib).
source $CURRENT_PATH/lib
#
#
#
#
#=========================================================================
# Exercise definition
#=========================================================================
# Suppose that X company sell flights through a web site and would like
# to grant points for each time that a client buy a flight giving their
# clients the opportunity to use these points in the following purchase.
#  Guidelines:
#    1. The entity grant points to clients from a backup amount in real money.
#    2. Points can be tranfered between clients.
#    3. When a client spent N points there are transfered to an entity
#      acount to control the amount of spent points.
#=========================================================================
#
#
#
#
#-------------------------------------------------------------------------
# First must define the scenario of the problem
#-------------------------------------------------------------------------
# Sign_in as system_admin user...
TOKEN=$(sign_in $SYSTEM_ADMIN $PASSWORD)

# Create and entity_admin for X company...
mix cli.users.create $TOKEN $ENTITY_ADMIN $PASSWORD entity_admin Adrian Marino

# Create X company...
mix cli.entities.create $TOKEN X "X company"

# Create backup account for issuer user under ARS currency...
mix cli.accounts.create $TOKEN $ENTITY_ADMIN ARS backup

# Create two normal users...
mix cli.users.create $TOKEN $NORMAL_USER_A $PASSWORD normal_user FirstNameA LastNameA
mix cli.users.create $TOKEN $NORMAL_USER_B $PASSWORD normal_user FirstNameB LastNameB

# Sign_out
sign_out $TOKEN


# Sign_in as entity_admin user...
TOKEN=$(sign_in $ENTITY_ADMIN $PASSWORD)

# Create a virtual currency under entity...
mix cli.currencies.create $TOKEN XPT "X points"

# Create exchange rate between ARS and XPT: "1 ARS <=> 1000 XPT"...
mix cli.exchange_rates.create $TOKEN ARS XPT 1000

# Create an account to control the amount of XPT points to spent for users with account under X company.
mix cli.accounts.create $TOKEN $ENTITY_ADMIN XPT

# Create two accounts for users A and B in X company under XPT currency...
mix cli.accounts.create $TOKEN $NORMAL_USER_A XPT
mix cli.accounts.create $TOKEN $NORMAL_USER_B XPT

# Deposit 10.000 ARS to backup account...
AMOUNT=10000
print "Deposit $AMOUNT ARS to $ENTITY_ADMIN backup account."
mix cli.transactions.exec.deposit $TOKEN \
  '{"to":{"email":"'"$ENTITY_ADMIN"'","currency":"ARS"},"amount":'"$AMOUNT"'}'
#
#
#
#
#-------------------------------------------------------------------------
# Resolution
#-------------------------------------------------------------------------
# 1. The entity grant points to client from a backup amount in real money.
# Transfer 10.0000 XPT to NORMAL_USER_A...
AMOUNT=10
print "Grant $AMOUNT ARS in points to $NORMAL_USER_A..."
mix cli.transactions.exec.transfer $TOKEN \
  '{"from":{"email":"'"$ENTITY_ADMIN"'","currency":"ARS"},"to":{"email":"'"$NORMAL_USER_A"'","currency":"XPT"},"amount":'"$AMOUNT"'}'
#
#
# 2. Points can be tranfered between clients.
# Transfer 5.000 XPT from NORMAL_USER_A to NORMAL_USER_B...
AMOUNT=5000
print "Transfer $AMOUNT X points from $NORMAL_USER_A to $NORMAL_USER_B..."
mix cli.transactions.exec.transfer $TOKEN \
  '{"from":{"email":"'"$NORMAL_USER_A"'","currency":"XPT"},"to":{"email":"'"$NORMAL_USER_B"'","currency":"XPT"},"amount":'"$AMOUNT"'}'
#
#
# 3. Then a client spent 2500 points there are transfered to an entity
#    acount to control the amount of spent points.
AMOUNT=2500
print "$NORMAL_USER_A user spent $AMOUNT X points..."
mix cli.transactions.exec.transfer $TOKEN \
  '{"from":{"email":"'"$NORMAL_USER_B"'","currency":"XPT"},"to":{"email":"'"$ENTITY_ADMIN"'","currency":"XPT"},"amount":'"$AMOUNT"'}'
#
#
# Show final state for all acounts...
print "Final accounts state..."
mix cli.accounts.show $TOKEN $ENTITY_ADMIN ARS
mix cli.accounts.show $TOKEN $ENTITY_ADMIN XPT
mix cli.accounts.show $TOKEN $NORMAL_USER_A XPT
mix cli.accounts.show $TOKEN $NORMAL_USER_B XPT
#
#
sign_out $TOKEN
